# Generated by Django 2.0.13 on 2019-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('currency', models.CharField(choices=[('dollar', 'dollar -> toman'), ('bitcoin', 'bitcoin -> dollar')], max_length=60, verbose_name='ارز')),
                ('amount', models.IntegerField(verbose_name='مقدار')),
            ],
        ),
    ]
