# Generated by Django 2.0.13 on 2019-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.IntegerField(editable=False, verbose_name='مقدار'),
        ),
    ]
