# Generated by Django 2.0.13 on 2019-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_auto_20190426_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd -> toman'), ('bitcoin', 'bitcoin -> usd')], max_length=60, verbose_name='ارز'),
        ),
    ]
