# Generated by Django 2.0.13 on 2019-04-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_account_actions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
    ]
