# Generated by Django 2.0.13 on 2019-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0005_auto_20190428_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='amount',
            new_name='transaction_amount',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('sell', 'sell bitcoin'), ('buy', 'buy bitcoin')], editable=False, max_length=60, verbose_name='نوع تراکنش'),
        ),
    ]
