# Generated by Django 2.0.13 on 2019-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0007_auto_20190430_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bitcoint_ammount',
            field=models.FloatField(editable=False, verbose_name='مقدار بیت کوین'),
        ),
    ]
