# Generated by Django 2.0.13 on 2019-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0008_auto_20190430_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='transaction_amount',
        ),
        migrations.AddField(
            model_name='action',
            name='bitcoin_transaction_amount',
            field=models.FloatField(default=0, editable=False, verbose_name='مقدار بیت کوین معامله شده'),
            preserve_default=False,
        ),
    ]
